sudo: required
services:
  - docker

before_install:
  - docker build -t adammarczyk/docker-react -f Dockerfile.dev .

script:
  - docker run adammarczyk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-842277445148'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
